<?php


namespace app\manage\model;

use AlibabaCloud\Client\AlibabaCloud;
use AlibabaCloud\Client\Exception\ClientException;
use AlibabaCloud\Client\Exception\ServerException;
use think\Db;
use think\facade\Config;
use think\facade\Request;
class Verification extends \think\Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $phone    电话
     * @param $userId   用户ID
     * @param $type 类型 短信的类型  1验证  2找回密码  3更换手机  默认1[非必填]
     * @return \think\response\Json
     * @throws ClientException
     * @throws \think\exception\DbException
     */
    public function send($phone='18613151357',$codes='SMS_178585256'){
//        echo Config::get("config_set.sms_code_name");
        //获取用户验证码信息
//        $verification = self::get(['phone' => $phone , 'uid' => $userId , 'state' => $type]);
        //查询用户是否已经验证过
        /**if(!empty($verification)){
            return error('验证码已发送，请等待',20001);
        }**/
        //查询code是否存在 存在的话 再次随机
        do{
            $code = getCode(null);
        }while(
            self::get(['code' => $code])
        );
        //阿里云的appkey
        AlibabaCloud::accessKeyClient('LTAI4FfAez4GdS8PkKTJ4Pz5', 'RevxGyoicQDrWQUDuyUlTP3pIoY7e0')
            ->regionId('cn-hangzhou')
            ->asDefaultClient();
        try {
            $result = AlibabaCloud::rpc()
                ->product('Dysmsapi')
                // ->scheme('https') // https | http
                ->version('2017-05-25')
                ->action('SendSms')
                ->method('POST')
                ->host('dysmsapi.aliyuncs.com')
                ->options([
                    'query' => [
                        'RegionId' => "cn-hangzhou",
                        'PhoneNumbers' => $phone,
                        'SignName' =>Config::get("config_set.sms_code_name"),   //短信签名名称
                        'TemplateCode' => $codes,//"SMS_172800162",  //短信模板ID
//                        'TemplateParam' => '{"code":"'.$code.'"}',  //验证码 json格式
                    ],
                ])
                ->request();
            //转换数组
            $data = $result->toArray();
//            dump($data);
            if($data['Message'] != 'OK'){

                return  false;
//                return error($data['Message'],$data['Code']);
            }else{
                //判断是否用同样类型以及同样Id的验证码 如果有 就更新 反之增加
//                if(!empty($verification)){
//                    $verification->code = $code;
//                    $verification->time = time();
//                }else {
//                    $verification = $this;
//                    $verification->state = $type;
//                    $verification->uid= $userId;
//                    $verification->phone = $phone;
//                    $verification->code = $code;
//                    $verification->time = time();
//                }
//                if($verification->save()){
                    return  true;
//                    return json_encode(['centon'=>'验证成功','msg'=>200]);
//                }else{
//                    return  false;
//                    return json_encode(['centon'=>'验证失败','msg'=>500]);
//                }
            }
        } catch (ClientException $e) {
            echo $e->getErrorMessage() . PHP_EOL;
        } catch (ServerException $e) {
            echo $e->getErrorMessage() . PHP_EOL;
        }
    }
    //查询发送记录
    public function smssendinfo($phone,$senddate){

        AlibabaCloud::accessKeyClient('LTAI4FcLfWBaZ9ovWx4RuEGw', 'pEqjvGiYZQQGE2vwlrQhNQvAwKKxj2')
            ->regionId('cn-hangzhou')
            ->asDefaultClient();

        try {
            $result = AlibabaCloud::rpc()
                ->product('Dysmsapi')
                // ->scheme('https') // https | http
                ->version('2017-05-25')
                ->action('QuerySendDetails')
                ->method('POST')
                ->host('dysmsapi.aliyuncs.com')
                ->options([
                    'query' => [
                        'RegionId' => "cn-hangzhou",
                        'PhoneNumber' =>$phone,
                        'SendDate' => $senddate,
                        'PageSize' => "50",
                        'CurrentPage' => "1",
//                        'TemplateCode' => "SMS_177551313",
                    ],
                ])
                ->request();
            $data=$result->toArray();
            return $data;
            } catch (ClientException $e) {
            echo $e->getErrorMessage() . PHP_EOL;
        } catch (ServerException $e) {
            echo $e->getErrorMessage() . PHP_EOL;
        }

    }
    /**
     * @param $code     验证码
     * @param $phone    电话
     * @param $userId   用户ID
     * @param $type 类型  1验证  2找回密码  3更换手机  默认1[非必填]
     * @return \think\response\Json
     * @throws \think\exception\DbException
     */
    public function codeVerification($code,$phone,$userId,$type){
        //获取用户验证码信息
        $verification = self::get(['phone' => $phone , 'uid' => $userId , 'state' => $type ,'code' => $code]);
        //获取用户信息
        $userInfo = User::get($userId);
        if($userInfo->is_phone == 2){
            return error('请勿重新验证',20001);
        }
        if($verification && $userInfo){
            $userInfo->phone = $phone;
            $userInfo->is_phone = 2;
            if($userInfo->save()){
                return success('success',200);
            }else{
                return error('用户信息更新错误',20001);
            }
        }else{
            return error('查询信息错误',20001);
        }
    }
}